# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLAD_config = debug
  Ivy_config = debug
  Sandbox_config = debug
endif
ifeq ($(config),release)
  GLAD_config = release
  Ivy_config = release
  Sandbox_config = release
endif

PROJECTS := GLAD Ivy Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C projects/Ivy/dependencies/GLAD -f Makefile config=$(GLAD_config)
endif

Ivy: GLAD
ifneq (,$(Ivy_config))
	@echo "==== Building Ivy ($(Ivy_config)) ===="
	@${MAKE} --no-print-directory -C projects/Ivy -f Makefile config=$(Ivy_config)
endif

Sandbox: Ivy GLAD
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C projects/Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C projects/Ivy/dependencies/GLAD -f Makefile clean
	@${MAKE} --no-print-directory -C projects/Ivy -f Makefile clean
	@${MAKE} --no-print-directory -C projects/Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLAD"
	@echo "   Ivy"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"