-- Helper Functions

function useIvyLib()
	-- The library's public headers
	includedirs "Projects/Ivy"
	
	-- We link against a library that's in the same workspace, so we can just
	-- use the project name - premake is really smart and will handle everything for us.
	links "Ivy"
end

-- The name of your workspace will be used, for example, to name the Visual Studio .sln file generated by Premake.
workspace "Ivy"
	-- We set the location of the files Premake will generate
	
	-- We indicate that all the projects are C++ only
	language "C++"
	-- Language standard should be C++17
	cppdialect "C++17"
	
	-- We will compile for x86_64. You can change this to x86 for 32 bit builds.
	architecture "x86_64"
	
	-- Configurations are often used to store some compiler / linker settings together.
    -- The Debug configuration will be used by us while debugging.
    -- The optimized Release configuration will be used when shipping the app.
	configurations { "Debug", "Release" }
	
	-- We use filters to set options, a new feature of Premake5.
	
	-- We now only set settings for the Debug configuration
	filter { "configurations:Debug" }
		-- We want debug symbols in our debug config
		symbols "On"
	
	-- We now only set settings for Release
	filter { "configurations:Release" }
		-- Release should be optimized
		optimize "On"
	
	-- Reset the filter for other settings
	filter { }
	
	-- Here we use some "tokens" (the things between %{ ... }). They will be replaced by Premake
	-- automatically when configuring the projects.
	-- * %{prj.name} will be replaced by "ExampleLib" / "App" / "UnitTests"
	--  * %{cfg.longname} will be replaced by "Debug" or "Release" depending on the configuration
	-- The path is relative to *this* folder
	targetdir ("Build/Bin/%{prj.name}/%{cfg.longname}")
	objdir ("Build/Obj/%{prj.name}/%{cfg.longname}")
	
-- The core engine, the static library
project "GLAD"
	
	location "Projects/Ivy/dependencies/GLAD"
	
	targetdir ("Projects/Ivy/dependencies/GLAD/Lib")
	objdir ("Projects/Ivy/dependencies/GLAD/Lib")
	
	kind "StaticLib"
	
	language "C"

	files
	{
		"Projects/Ivy/dependencies/GLAD/include/glad/glad.h",
		"Projects/Ivy/dependencies/GLAD/include/KHR/khrplatform.h",
		"Projects/Ivy/dependencies/GLAD/src/glad.c"
	}
	
	includedirs "Projects/Ivy/dependencies/GLAD/include"
	
	filter "configurations:Debug"
        runtime "Debug"
        symbols "on"

    filter "configurations:Release"
        runtime "Release"
        optimize "on"
		
	filter{ }	

-- The core engine, the static library
project "Ivy"
	
	location "projects/Ivy"
	
	-- kind is used to indicate the type of this project.
	kind "StaticLib"
	
	includedirs
	{
		"Projects/Ivy/source",
		"Projects/Ivy/dependencies/GLFW/Include",
		"Projects/Ivy/dependencies/GLAD/include",
		"Projects/Ivy/dependencies/spdlog/include",
		"Projects/Ivy/dependencies/glm"
	}
	
	libdirs
	{
		"Projects/Ivy/dependencies/GLFW/Lib",
		"Projects/Ivy/dependencies/GLAD/Lib"
	}
	
	links
	{
		links "GLAD",
		links "GLFW3"
	}

	-- We specify where the source files are.
	-- It would be better to separate header files in a folder and sources
	-- in another, but for our simple project we will put everything in the same place.
	-- Note: ** means recurse in subdirectories, so it will get all the files in ExampleLib/
	pchheader "ivypch.h"
    pchsource "Projects/Ivy/source/ivypch.cpp"
	files "Projects/Ivy/source/**"
	

-- The windowed sandbox app
project "Sandbox"

	location "projects/Sandbox"
	
	kind "ConsoleApp"
	files "Projects/Sandbox/source/**"

	-- We also need the headers
	includedirs "Projects/Ivy/source"
	includedirs "Projects/Ivy/dependencies/GLFW/Include"
	includedirs "Projects/Ivy/dependencies/GLAD/include"
	includedirs "Projects/Ivy/dependencies/spdlog/include"
	includedirs "Projects/Ivy/dependencies/glm"
	
	
	links "Ivy"
	
